services:
    dm.ajaxcom:
        class: DM\AjaxCom\Handler
        public: false

    ajaxcom.handler:
        class: Everlution\AjaxcomBundle\Ajaxcom
        arguments:
            - '@dm.ajaxcom'
            - '@session'
            - '@twig'
            - '@router'
            - '%everlution.ajaxcom.flash_template%'
            - '%everlution.ajaxcom.flash_block_id%'
            - '%everlution.ajaxcom.persistent_class%'
            - '%everlution.ajaxcom.blocks_to_render%'
