services:
    ajaxcom.handler:
        class: Everlution\AjaxcomBundle\Service\Ajaxcom
        public: true
        arguments:
            - '@everlution.ajaxcom'
            - '@ajaxcom.mutation.containe'

    everlution.ajaxcom:
        class: Everlution\Ajaxcom\Handler
        public: true

    ajaxcom.render_block:
        class: Everlution\AjaxcomBundle\Service\RenderBlock
        public: false
        arguments:
            - '@twig'

    # mutations
    ajaxcom.mutation.containe:
        class: Everlution\AjaxcomBundle\Mutation\Container
        # the order of following call is important
        calls:
            - ['add', ['@ajaxcom.mutation.replace_style_sheets']]
            - ['add', ['@ajaxcom.mutation.replace_meta_tags']]
            - ['add', ['@ajaxcom.mutation.replace_title']]
            - ['add', ['@ajaxcom.mutation.flash_messages']]
            - ['add', ['@ajaxcom.mutation.remove_blocks']]
            - ['add', ['@ajaxcom.mutation.append_blocks']]
            - ['add', ['@ajaxcom.mutation.prepend_blocks']]
            - ['add', ['@ajaxcom.mutation.add_blocks']]
            - ['add', ['@ajaxcom.mutation.replace_class']]
            - ['add', ['@ajaxcom.mutation.replace_java_scripts']]
            - ['add', ['@ajaxcom.mutation.callbacks']]
            - ['add', ['@ajaxcom.mutation.change_url']]

    ajaxcom.mutation.append_blocks:
        class: Everlution\AjaxcomBundle\Mutation\AppendBlocks
        arguments:
            - '@ajaxcom.render_block'

    ajaxcom.mutation.prepend_blocks:
        class: Everlution\AjaxcomBundle\Mutation\PrependBlocks
        arguments:
            - '@ajaxcom.render_block'

    ajaxcom.mutation.add_blocks:
        class: Everlution\AjaxcomBundle\Mutation\AddBlocks
        public: true
        arguments:
            - '@ajaxcom.render_block'
            - '%everlution.ajaxcom.blocks_to_render%'

    ajaxcom.mutation.replace_content:
        class: Everlution\AjaxcomBundle\Mutation\ReplaceContent
        public: true
        arguments:
            - '@ajaxcom.render_block'

    ajaxcom.mutation.remove_blocks:
        class: Everlution\AjaxcomBundle\Mutation\RemoveBlocks
        public: true

    ajaxcom.mutation.callbacks:
        class: Everlution\AjaxcomBundle\Mutation\Callbacks
        public: true
        arguments:
            - '@session'

    ajaxcom.mutation.replace_class:
        class: Everlution\AjaxcomBundle\Mutation\ReplaceClass
        public: true
        arguments:
            - '@ajaxcom.render_block'

    ajaxcom.mutation.change_url:
        class: Everlution\AjaxcomBundle\Mutation\ChangeUrl
        public: true
        arguments:
            - '@request_stack'
            - '@router.default'
            - '%everlution.ajaxcom.change_url%'

    ajaxcom.mutation.flash_messages:
        class: Everlution\AjaxcomBundle\Mutation\FlashMessages
        public: false
        arguments:
            - '@ajaxcom.render_block'
            - '@session.flash_bag'
            - '%everlution.ajaxcom.flash_template%'
            - '%everlution.ajaxcom.flash_block_id%'

    ajaxcom.mutation.replace_java_scripts:
        class: Everlution\AjaxcomBundle\Mutation\ReplaceJavaScripts
        public: false
        arguments:
            - '@ajaxcom.render_block'
            - '%everlution.ajaxcom.persistent_class%'

    ajaxcom.mutation.replace_meta_tags:
        class: Everlution\AjaxcomBundle\Mutation\ReplaceMetaTags
        public: false
        arguments:
            - '@ajaxcom.render_block'
            - '%everlution.ajaxcom.persistent_class%'

    ajaxcom.mutation.replace_style_sheets:
        class: Everlution\AjaxcomBundle\Mutation\ReplaceStyleSheets
        public: false
        arguments:
            - '@ajaxcom.render_block'
            - '%everlution.ajaxcom.persistent_class%'

    ajaxcom.mutation.replace_title:
        class: Everlution\AjaxcomBundle\Mutation\ReplaceTitle
        public: false
        arguments:
            - '@ajaxcom.render_block'

    # Symfony 4 autowiring compat
    Everlution\AjaxcomBundle\Service\Ajaxcom: '@ajaxcom.handler'
    Everlution\Ajaxcom\Handler: '@everlution.ajaxcom'
    Everlution\AjaxcomBundle\Service\RenderBlock: '@ajaxcom.render_block'
    Everlution\AjaxcomBundle\Mutation\Container: '@ajaxcom.mutation.containe'
    Everlution\AjaxcomBundle\Mutation\AppendBlocks: '@ajaxcom.mutation.append_blocks'
    Everlution\AjaxcomBundle\Mutation\PrependBlocks: '@ajaxcom.mutation.prepend_blocks'
    Everlution\AjaxcomBundle\Mutation\AddBlocks: '@ajaxcom.mutation.add_blocks'
    Everlution\AjaxcomBundle\Mutation\ReplaceContent: '@ajaxcom.mutation.replace_content'
    Everlution\AjaxcomBundle\Mutation\RemoveBlocks: '@ajaxcom.mutation.remove_blocks'
    Everlution\AjaxcomBundle\Mutation\Callbacks: '@ajaxcom.mutation.callbacks'
    Everlution\AjaxcomBundle\Mutation\ReplaceClass: '@ajaxcom.mutation.replace_class'
    Everlution\AjaxcomBundle\Mutation\ChangeUrl: '@ajaxcom.mutation.change_url'
    Everlution\AjaxcomBundle\Mutation\FlashMessages: '@ajaxcom.mutation.flash_messages'
    Everlution\AjaxcomBundle\Mutation\ReplaceJavaScripts: '@ajaxcom.mutation.replace_java_scripts'
    Everlution\AjaxcomBundle\Mutation\ReplaceMetaTags: '@ajaxcom.mutation.replace_meta_tags'
    Everlution\AjaxcomBundle\Mutation\ReplaceStyleSheets: '@ajaxcom.mutation.replace_style_sheets'
    Everlution\AjaxcomBundle\Mutation\ReplaceTitle: '@ajaxcom.mutation.replace_title'
